name: Test
"on":
  push:
    branches:
      - master
      - dependabot/npm_and_yarn/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  npmCi:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm test
  typecheck:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: cd payload-examples && npm i && cd ..
      - run: npm run typecheck
  do-types-need-regenerating:
    name: Do types need to be regenerated?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:schema
      - run: npm run build:types
      - run: git status
      - run: |
          git diff --exit-code || bash -c \
            'echo "::error file=schema.d.ts::This needs to be regenerated by running \`build:types\`" && false'
  do-examples-need-regenerating:
    name: Do examples need to be regenerated?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:webhooks -- --check --cached
      - run: git status
      - run: |
          git diff --exit-code || bash -c \
            'echo "::error file=api.github.com/index.json::This needs to be regenerated by running \`build:webhooks -- --cached\`" && false'
